# docker run --privileged --name vins-con -e DISPLAY=$DISPLAY -e QT_X11_NO_MITSHM=1 
# --network host -v /tmp/.X11-unix:/tmp/.X11-unix -v /dev:/dev:ro 
# -v ~/.Xauthority:/root/.Xauthority -it vins

version: '3.3'
services:
    vins:
        privileged: true
        container_name: vins-con
        environment:
            - DISPLAY=$DISPLAY
            - QT_X11_NO_MITSHM=1
        network_mode: host
        volumes:
            - '/tmp/.X11-unix:/tmp/.X11-unix'
            - '/dev:/dev:ro'
            - '$HOME/.Xauthority:/root/.Xauthority:rw'
        stdin_open: true
        tty: true
        image: vins

# docker run --privileged --name vins-con -e DISPLAY=$DISPLAY -e QT_X11_NO_MITSHM=1 --network host -v /tmp/.X11-unix:/tmp/.X11-unix -v /dev:/dev:ro -v ~/.Xauthority:/root/.Xauthority -it vins